type: object
properties:
  idUser:
    type: integer
    description: Fonctionnel id of the user
    format: int64
  productList:
    type: array
    description: The List of the ProductResultDTO by user
    items:
      $ref: './ProductDTO.yml'