server:
  port: 8081
  servlet:
    context-path: /api

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dbadminapp?createDatabaseIfNotExist=true
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
  application:
    name: spring-admin

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true


info:
  application:
    name: admin-app-openapi
    version: '@project.version@'