/**
 * API Admin-app
 * Microservice pour une admin-app de openAPI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RoleDTO { 
    /**
     * Fonctionnel id of the role.
     */
    idRole?: number;
    /**
     * Name of the role.
     */
    name?: string;
}

