/**
 * API Admin-app
 * Microservice pour une admin-app de openAPI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserDTO { 
    /**
     * Fonctionnel id of the user.
     */
    idUser?: number;
    /**
     * firstname of the user.
     */
    firstname?: string;
    /**
     * lastname of the user.
     */
    lastname?: string;
    /**
     * email of the user.
     */
    email?: string;
    /**
     * password of the user.
     */
    password?: string;
}

