/**
 * API Admin-app
 * Microservice pour une admin-app de openAPI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { UserDTO } from '../model/models';
import { UserResultListByRoleDTO } from '../model/models';
import { UsersResultListDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface UsersServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Add a user
     * 
     * @param userDTO 
     */
    createAppUser(userDTO?: UserDTO, extraHttpRequestParams?: any): Observable<UserDTO>;

    /**
     * Get All Actifs Users
     * 
     * @param currentPage 
     * @param sizePage 
     */
    getAllAppUser(currentPage: number, sizePage: number, extraHttpRequestParams?: any): Observable<UsersResultListDTO>;

    /**
     * Get All Actifs Users by role
     * 
     * @param currentPage 
     * @param sizePage 
     */
    getAppAllUserByRole(currentPage: number, sizePage: number, extraHttpRequestParams?: any): Observable<UserResultListByRoleDTO>;

    /**
     * Retrieve an user
     * 
     * @param idUser 
     */
    getAppUser(idUser: number, extraHttpRequestParams?: any): Observable<UserDTO>;

    /**
     * Add a user
     * 
     * @param idUser 
     * @param userDTO 
     */
    updateAppUser(idUser: number, userDTO?: UserDTO, extraHttpRequestParams?: any): Observable<UserDTO>;

}
